# # This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# # For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# # name: Node.js Package

# # on:
# #   release:
# #     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16


#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           registry-url: https://npm.pkg.github.com/
#       - name: Install dependencies
#         run: npm i
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

# permissions:
#   contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN}}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      id: autobump
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        # preset: 'angular'
        # tag-prefix: 'mb'
        output-file: "false"
        skip-on-empty: 'true'
    - name: Create Release
      # uses: softprops/action-gh-release@v1  #actions/create-release@v1
      # if: ${{ steps.changelog.outputs.skipped == 'false' }}
      # env:
      #   GITHUB_TOKEN: ${{ secrets.github_token }}
      # with:
      #   tag_name: ${{ steps.changelog.outputs.tag }}
      #   release_name: ${{ steps.changelog.outputs.tag }}
      #   body: ${{ steps.changelog.outputs.clean_changelog }}
      #   token: ${{ github.token }}
      run: echo ${{ steps.autobump.outputs.version}}
    #   uses: elgohr/Github-Release-Action@v4
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     title: MyTitle
    #     tag_name: ${{ steps.changelog.outputs.tag }}
    #     release_name: ${{ steps.changelog.outputs.tag }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: 16
    #     registry-url: https://npm.pkg.github.com/
    # - name: Install dependencies
    #   run: npm i
    # - name: Publish
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

